Member/myprojectface/members/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/', views.add_member, name='add_member'),
    path('member_list', views.member_list, name='member_list'),
    path('scan/', views.scan_face, name='scan_face'),
    path('delete/<int:member_id>/', views.delete_member, name='delete_member'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('check_faces/', views.check_faces, name='check_faces'),
    path('edit/<int:member_id>/', views.edit_member, name='edit_member'),
    path('register/', views.register, name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.auth_views.LogoutView.as_view(), name='logout'),
    path('', views.home, name='home'),
    path('user_list/', views.user_list, name='user_list'),
    path('user/<int:user_id>/', views.user_edit, name='user_edit'),
    path('delete_user/<int:user_id>/', views.user_delete, name='user_delete'),
]

Member/myprojectface/myprojectface/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('members.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Member/myprojectface/members/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    MANAGER = 'manager'
    CASHIER = 'cashier'
    ROLE_CHOICES = [
        (MANAGER, 'Manager'),
        (CASHIER, 'Cashier'),
    ]

    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default=CASHIER)
    email = models.EmailField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    photo_profile = models.ImageField(upload_to='profile_photos/', blank=True, null=True)

    def __str__(self):
        return self.username
    
class Member(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    details = models.TextField(blank=True, null=True)
    face_image = models.ImageField(upload_to='face_images/', blank=True, null=True)
    face_encoding = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class CustomerVisit(models.Model):
    date = models.DateField(auto_now_add=True)  # วันที่ลูกค้าเข้ามา
    member = models.ForeignKey(Member, on_delete=models.CASCADE, null=True, blank=True)  # ถ้าเป็นสมาชิกจะเก็บข้อมูลสมาชิก
    is_member = models.BooleanField(default=False)  # บอกว่าลูกค้าเป็นสมาชิกหรือไม่

    def __str__(self):
        return f"{self.date} - {'Member' if self.is_member else 'Non-member'}"

Member/myprojectface/members/forms.py
# members/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'phone_number', 'photo_profile', 'role')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'phone_number', 'photo_profile', 'role')

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'phone_number', 'photo_profile', 'role')
        
class MemberForm(forms.ModelForm):
    photo_data = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    class Meta:
        model = Member
        fields = ['name', 'phone_number', 'details']

Member/myprojectface/members/views.py
# members/views.py

import base64
import face_recognition
import numpy as np
from django.contrib.auth import views as auth_views
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count
from django.utils import timezone
from django.http import JsonResponse
import datetime
from .models import *
from .forms import *

def is_manager(user):
    return user.role == 'manager'

@login_required
@user_passes_test(is_manager)
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            return redirect('user_list')
    else:
        form = CustomUserCreationForm()
    return render(request, 'members/register.html', {'form': form})

@login_required
def home(request):
    return render(request, 'members/scan_face.html', {'user': request.user,})

class CustomLoginView(auth_views.LoginView):
    template_name = 'members/login.html'

@login_required
@user_passes_test(is_manager)
def user_list(request):
    managers = CustomUser.objects.filter(role='manager')
    cashiers = CustomUser.objects.filter(role='cashier')
    users = list(managers) + list(cashiers)
    return render(request, 'members/user_list.html', {'users': users})

@login_required
@user_passes_test(is_manager)
def user_edit(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user_list')
    else:
        form = UserUpdateForm(instance=user)
    return render(request, 'members/edit_user.html', {'form': form, 'user': user})

@login_required
@user_passes_test(is_manager)
def user_delete(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    if request.method == 'POST':
        user.delete()
        return redirect('user_list')
    return redirect('user_list')

@login_required
def add_member(request):
    error = None  # กำหนดตัวแปร error เป็น None
    if request.method == 'POST':  # ตรวจสอบว่าคำขอเป็นแบบ POST หรือไม่
        form = MemberForm(request.POST, request.FILES)  # รับข้อมูลจากฟอร์ม
        if form.is_valid():  # ตรวจสอบว่าฟอร์มถูกต้องหรือไม่
            member = form.save(commit=False)  # สร้างออบเจ็กต์ Member แต่ยังไม่บันทึกลงฐานข้อมูล
            photo_data = form.cleaned_data.get('photo_data')  # รับข้อมูลรูปภาพจากฟอร์ม
            
            if photo_data:  # ตรวจสอบว่ามีข้อมูลรูปภาพหรือไม่
                format, imgstr = photo_data.split(';base64,')  # แยกส่วนที่เป็นรูปแบบและข้อมูลที่เข้ารหัส Base64 ออกจากกัน
                ext = format.split('/')[-1]  # ดึงนามสกุลไฟล์จากรูปแบบ
                member.face_image.save(f'{member.name}.{ext}', ContentFile(base64.b64decode(imgstr)), save=False)  # บันทึกภาพใบหน้า
            
                if member.face_image:  # ตรวจสอบว่ามีการบันทึกภาพใบหน้าแล้วหรือไม่
                    image = face_recognition.load_image_file(member.face_image)  # โหลดรูปภาพ
                    face_encodings = face_recognition.face_encodings(image, num_jitters=5, model='large')  # ดึง face encodings จากรูปภาพ
                    if len(face_encodings) > 1:  # ตรวจสอบว่ามีใบหน้ามากกว่าหนึ่งใบหน้าหรือไม่
                        error = 'พบใบหน้ามากกว่าหนึ่งใบหน้าในภาพ กรุณาอัปโหลดภาพที่มีใบหน้าเพียงใบหน้าเดียว'
                    elif len(face_encodings) == 1:  # ตรวจสอบว่ามีใบหน้าเพียงหนึ่งใบหน้าหรือไม่
                        member.face_encoding = np.array2string(face_encodings[0])  # เก็บ face encoding เป็นสตริง
                        member.save()  # บันทึกสมาชิกลงฐานข้อมูล
                        return redirect('scan_face')  # ย้ายไปหน้ารายการสมาชิก
                    else:  # ไม่พบใบหน้าในภาพ
                        error = 'ไม่พบใบหน้าในภาพ กรุณาอัปโหลดภาพที่มีใบหน้า'
    
    else:
        form = MemberForm()  # สร้างฟอร์มเปล่า
    return render(request, 'members/add_member.html', {'form': form, 'error': error})  # แสดงฟอร์มเพื่อเพิ่มสมาชิกพร้อมข้อความข้อผิดพลาด (ถ้ามี)

@login_required
def check_faces(request):
    if request.method == 'POST':  # ตรวจสอบว่าคำขอเป็นแบบ POST หรือไม่
        photo_data = request.POST.get('photo_data')  # รับข้อมูลรูปภาพจากคำขอ POST
        if photo_data:  # ตรวจสอบว่ามีข้อมูลรูปภาพหรือไม่
            format, imgstr = photo_data.split(';base64,')  # แยกส่วนที่เป็นรูปแบบและข้อมูลที่เข้ารหัส Base64 ออกจากกัน
            ext = format.split('/')[-1]  # ดึงนามสกุลไฟล์จากรูปแบบ
            image_data = base64.b64decode(imgstr)  # ถอดรหัสข้อมูล Base64 เป็นข้อมูลไบนารี
            # โหลดรูปภาพจากข้อมูลไบนารี
            image = face_recognition.load_image_file(ContentFile(image_data, 'scan_image.' + ext))
            # ดึง face encodings จากรูปภาพด้วยการตั้งค่า num_jitters และ model
            face_encodings = face_recognition.face_encodings(image, num_jitters=1, model='small')
            
            if len(face_encodings) > 1:  # ตรวจสอบว่ามีใบหน้ามากกว่าหนึ่งใบหน้าหรือไม่
                return JsonResponse({'error': 'พบใบหน้ามากกว่าหนึ่งใบหน้าในภาพ กรุณาอัปโหลดภาพที่มีใบหน้าเพียงใบหน้าเดียว'})
            elif len(face_encodings) == 0:  # ตรวจสอบว่าไม่พบใบหน้าในภาพหรือไม่
                return JsonResponse({'error': 'ไม่พบใบหน้าในภาพ กรุณาอัปโหลดภาพที่มีใบหน้า'})
            else:  # พบใบหน้าเพียงหนึ่งใบหน้า
                return JsonResponse({'success': 'พบใบหน้าเพียงใบหน้าเดียวในภาพ'})
    return JsonResponse({'error': 'คำขอไม่ถูกต้อง'})

@login_required
def member_list(request):
    members = Member.objects.all()
    return render(request, 'members/member_list.html', {'members': members})

@login_required
def edit_member(request, member_id):
    member = get_object_or_404(Member, id=member_id)
    old_image_path = member.face_image.path if member.face_image else None
    error = None

    if request.method == 'POST':
        form = MemberForm(request.POST, request.FILES, instance=member)
        if form.is_valid():
            member = form.save(commit=False)
            photo_data = form.cleaned_data.get('photo_data')

            if photo_data:

                format, imgstr = photo_data.split(';base64,')
                ext = format.split('/')[-1]
                member.face_image.save(f'{member.name}.{ext}', ContentFile(base64.b64decode(imgstr)), save=False)

                if member.face_image:
                    image = face_recognition.load_image_file(member.face_image)
                    face_encodings = face_recognition.face_encodings(image, num_jitters=5, model='large')
                    if len(face_encodings) > 1:
                        error = 'พบใบหน้ามากกว่าหนึ่งใบหน้าในภาพ กรุณาอัปโหลดภาพที่มีใบหน้าเพียงใบหน้าเดียว'
                    elif len(face_encodings) == 1:
                        member.face_encoding = np.array2string(face_encodings[0])
                        member.save()
                        return redirect('member_list')
                    else:
                        error = 'ไม่พบใบหน้าในภาพ กรุณาอัปโหลดภาพที่มีใบหน้า'
            else:
                member.save()
                return redirect('member_list')

    else:
        form = MemberForm(instance=member)

    return render(request, 'members/edit_member.html', {'form': form, 'member': member, 'error': error})

@login_required
def scan_face(request):
    member = None
    error = None

    if request.method == 'POST':
        photo_data = request.POST.get('photo_data')
        if photo_data:
            format, imgstr = photo_data.split(';base64,')
            ext = format.split('/')[-1]
            image_data = base64.b64decode(imgstr)
            image = face_recognition.load_image_file(ContentFile(image_data, 'scan_image.' + ext))
            unknown_face_encodings = face_recognition.face_encodings(image, num_jitters=5 , model='large' )
            
            if unknown_face_encodings:
                unknown_face_encoding = unknown_face_encodings[0]
                members = Member.objects.all()
                for member in members:
                    if member.face_encoding:
                        known_face_encoding = np.fromstring(member.face_encoding[1:-1], sep=' ')
                        result_face = face_recognition.compare_faces([known_face_encoding], unknown_face_encoding,tolerance=0.4)[0]
                        if result_face == False:
                            error = 'No match found'
    
                        elif result_face == True:
                            distance = face_recognition.face_distance([known_face_encoding], unknown_face_encoding)[0]
                            similarity_percentage = (1 - distance) * 100
                            CustomerVisit.objects.create(date=timezone.now(), member=member, is_member=True)
                            return render(request, 'members/scan_face.html', {'member': member, 'similarity': similarity_percentage})
                
                CustomerVisit.objects.create(date=timezone.now(), is_member=False)
                return render(request, 'members/scan_face.html', {'error': error})
                            
            else:
                error = 'No face detected'
    
    return render(request, 'members/scan_face.html', {'member': member, 'error': error})

@login_required
def delete_member(request, member_id):
    member = get_object_or_404(Member, id=member_id)
    if request.method == 'POST':
        member.delete()
        return redirect('member_list')
    return redirect('member_list')

@login_required
@user_passes_test(is_manager)
def dashboard(request):
    today = timezone.localtime().date()
    visits_today = CustomerVisit.objects.filter(date=today).count()

Member/myprojectface/members/templates/members/add_member.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add member</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        .main {
            display: flex;
        }
        form {
            display: flex;
            
        }
        input ,textarea {
            width: 100%;
            padding: 10px;
            border: 2px solid #706EFB;
            border-radius: 15px;
            background-color: #fff;
            color: #19181c;
        }
        label {
            display: block;
            text-align: left;
            margin-top: 10px;
            margin-bottom: 10px;
            font-size: 1em;
        }
        .left-panel {
            flex: 1;
            padding: 30px;
        }
        .right-panel {
            flex: 1;
            padding: 30px;
            align-items: center;
        }
        .video-container {
            position: relative;
        }
        .video-container video {
            max-width: 750px;
            background: linear-gradient(#19181c, #19181c) padding-box, linear-gradient(180deg, #706EFB, #f93f64) border-box;
            border-radius: 2.5vh;
            border: 2px solid transparent;
        }
        .video-container canvas {
            max-width: 300px;
            width: 100%;
            
        }
        .result {
            width: 100%;
            min-height: 70vh;
            padding: 40px;
            background: linear-gradient(#19181c, #19181c) padding-box, linear-gradient(180deg, #706EFB, #f93f64) border-box;
            border-radius: 2.5vh;
            border: 1.5px solid transparent;
        }
        .result .title {
            font-weight: bold;
            margin-bottom: 10px;
            font-size: 24px;
        }
        .result div {
            margin-bottom: 10px;
            font-size: 18px;
        }
        .result img {
            max-width: 500px;
            margin-top: 10px;
        }
        .button-g button,.button-g a {
            margin: 20px;
            padding: 12.5px;
            background: linear-gradient(180deg, #F93F64,#706EFB);
            border: 2px solid #fff;
            border-radius: 2.5vh;
            color: #fff;
            font-size: 1em;
            cursor: pointer;
        }
        .button-g {
            padding: 1vh;
            display: flex;
        }
    </style>
</head>
<body>
    <!-- container start -->
    <div class="container">
        <!-- sidebar start -->
        <div class="sidebar">
            <div class="logo">
                <a href="/">
                    <img src="{% static 'images/logo.png'%}" alt="">
                </a>
            </div>
            <!-- Profile User -->
            <div class="profile">
                <div class="photo_profile">
                    {% if user.photo_profile %}
                        <img src="{{ user.photo_profile.url }}" alt="">
                    {% endif %}
                </div>
                <div>
                    <p>{{ user.first_name }}</p>
                    <p>{{ user.get_role_display }}</p>
                </div>
            </div>
            <div class="sidebar-menu">
                <a href="{% url 'scan_face' %}">
                    <i class="fa-solid fa-expand"></i>
                    สแกนหน้า
                </a>
                <a href="{% url 'member_list' %}"><i class="fa-regular fa-user"></i>รายชื่อสมาชิก</a>
                <a href="{% url 'register' %}"><i class="fa-solid fa-registered"></i>สมัครแคชเชียร์</a>
                <a href="{% url 'user_list' %}"><i class="fa-regular fa-user"></i>รายชื่อแคชเชียร์</a>
                <a href="{% url 'dashboard' %}">
                    <i class="fa-solid fa-chart-line"></i>
                    รายงานยอดลูกค้า
                </a>
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="logout-button">
                        <i class="fa-solid fa-arrow-right-from-bracket"></i>
                        ออกจากระบบ</button>
                </form>
            </div>            
        </div>
        <!-- sidebar end -->
        <div class="content">
            <!-- nav start -->
            <nav>
            </nav>
            <!-- nav end -->
            <!-- footer start -->
            <footer><h6>alpha tracking(c)</h6>
            </footer>

            <div class="main">
                <form method="post" enctype="multipart/form-data" id="member-form" >
                    {% csrf_token %}
                    <div class="left-panel">
                        <div id="result" class="result">
                            <h2>เพิ่มสมาชิก</h2>
                            {{ form.as_p }}
                            <div class="button-g">
                                <button type="button" onclick="takePicture()"><i class="fa-solid fa-camera"></i>ถ่ายรูป</button>
                                <input type="hidden" name="photo_data" id="photo_data">
                                <button type="submit" id="submit-btn" style="display:none;"><i class="fa-solid fa-check"></i>ยืนยัน</button>
                            </div>
                        </div>
                    </div>
                    <div class="right-panel">
                        <div class="video-container">
                            <video id="camera" autoplay></video>
                            <canvas id="photo"></canvas>
                        </div>
                        <p id="message" style="font-size: 18px;"></p>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        const video = document.getElementById('camera');
        const canvas = document.getElementById('photo');
        const photo_data = document.getElementById('photo_data');
        const message = document.getElementById('message');
        const submitBtn = document.getElementById('submit-btn');

        if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
            navigator.mediaDevices.getUserMedia({ video: true }).then(function(stream) {
                video.srcObject = stream;
                video.play();
            });
        }

        function takePicture() {
            const context = canvas.getContext('2d');
            const width = video.videoWidth;
            const height = video.videoHeight;
            canvas.width = width;
            canvas.height = height;
            context.drawImage(video, 0, 0, width, height);
            const data = canvas.toDataURL('image/png');
            photo_data.value = data;
            canvas.style.display = 'block';

            // ส่งข้อมูลรูปภาพผ่าน AJAX
            $.ajax({
                type: 'POST',
                url: '{% url "check_faces" %}',
                data: {
                    'photo_data': data,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    if (response.error) {
                        message.textContent = response.error;
                        submitBtn.style.display = 'none';  // ซ่อนปุ่ม submit ถ้ามีข้อผิดพลาด
                    } else {
                        message.textContent = response.success;
                        submitBtn.style.display = 'block';  // แสดงปุ่ม submit ถ้าไม่มีข้อผิดพลาด
                    }
                }
            });
        }
    </script>
</body>
</html>

Member/myprojectface/members/templates/members/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        
        .result {
            width: 100%;
            min-height: 70vh;
            padding: 40px;
            background: linear-gradient(#19181c, #19181c) padding-box, linear-gradient(180deg, #706EFB, #f93f64) border-box;
            border-radius: 2.5vh;
            border: 1.5px solid transparent;
        }
        .result .title {
            font-weight: bold;
            margin-bottom: 10px;
            font-size: 24px;
        }
        .result div {
            margin-bottom: 10px;
            font-size: 18px;
        }
        .result img {
            max-width: 500px;
            margin-top: 10px;
        }
        .button-g button,.button-g a {
            margin: 20px;
            padding: 12.5px;
            background: linear-gradient(180deg, #F93F64,#706EFB);
            border: 2px solid #fff;
            border-radius: 2.5vh;
            color: #fff;
            font-size: 1em;
            cursor: pointer;
        }
        .button-g {
            padding: 1vh;
            display: flex;
        }

    </style>
</head>
<body>
    <!-- container start -->
    <div class="container">
        <!-- sidebar start -->
        <div class="sidebar">
            <div class="logo">
                <a href="/">
                    <img src="{% static 'images/logo.png'%}" alt="">
                </a>
            </div>
            <!-- Profile User -->
            <div class="profile">
                <div class="photo_profile">
                    {% if user.photo_profile %}
                        <img src="{{ user.photo_profile.url }}" alt="">
                    {% endif %}
                </div>
                <div>
                    <p>{{ user.first_name }}</p>
                    <p>{{ user.get_role_display }}</p>
                </div>
            </div>
            <div class="sidebar-menu">
                <a href="{% url 'scan_face' %}">
                    <i class="fa-solid fa-expand"></i>
                    สแกนหน้า
                </a>
                <a href="{% url 'member_list' %}"><i class="fa-regular fa-user"></i>รายชื่อสมาชิก</a>
                <a href="{% url 'register' %}"><i class="fa-solid fa-registered"></i>สมัครแคชเชียร์</a>
                <a href="{% url 'user_list' %}"><i class="fa-regular fa-user"></i>รายชื่อแคชเชียร์</a>
                <a href="{% url 'dashboard' %}">
                    <i class="fa-solid fa-chart-line"></i>
                    รายงานยอดลูกค้า
                </a>
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="logout-button">
                        <i class="fa-solid fa-arrow-right-from-bracket"></i>
                        ออกจากระบบ</button>
                </form>
            </div>            
        </div>
        <!-- sidebar end -->
        <div class="content">
            <!-- nav start -->
            <nav>
            </nav>
            <!-- nav end -->
            <!-- footer start -->
            <footer><h6>alpha tracking(c)</h6>
            </footer>

            <div class="main">
                <div id="result" class="result">
                    <h1>รายงานยอดลูกค้า</h1>
                    <p>จำนวนลูกค้าวันนี้ : {{ visits_today }}</p>
                    <p>จำนวนสมาชิก : {{ member_visits_today }}</p>
                    <p>จำนวนไม่เป็นสมาชิก: {{ non_member_visits_today }}</p>
                    <canvas id="myChart" width="400" height="150"></canvas>
                </div>
            </div>
        </div>
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: {{ labels|safe }},
                datasets: [{
                    label: 'สมาชิก',
                    data: {{ member_data|safe }},
                    backgroundColor: 'rgba(75, 192, 192, 0.2)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1
                },
                {
                    label: 'ไม่เป็นสมาชิก',
                    data: {{ non_member_data|safe }},
                    backgroundColor: 'rgba(255, 99, 132, 0.2)',
                    borderColor: 'rgba(255, 99, 132, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    x: {
                        stacked: true  // กำหนดค่า stacked ให้กับแกน x
                    },
                    y: {
                        stacked: true  // กำหนดค่า stacked ให้กับแกน y
                    }
                }
            }
        });
    </script>
</body>
</html>

Member/myprojectface/members/templates/members/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Login</title>
</head>
<body>
    <!-- nav start -->
    <nav style="width: 100%;">
    </nav>
    <!-- nav end -->
    
    <div class="login-container">
        <div class="login-header">
            <img src="{% static 'images/logo.png' %}" alt="Alpha Tracking Logo" class="logo">
        </div>
        <form method="post" class="login-form">
            {% csrf_token %}
            <div class="form-group">
            {{ form.as_p }}
            </div>
            <button type="submit" class="login-button">LOGIN</button>
        </form>
        {% if error %}
            <p style="color: red;">{{ error }}</p>
        {% endif %}
    </div>
    
    <!-- footer start -->
    <footer style="width: 100%;"><h6>alpha tracking(c)</h6></footer>
    <!-- footer end -->
</body>
</html>